
server:
  port: 8040
  # 下面是配置undertow作为服务器的参数
#  undertow:
#    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
#    io-threads: 8
#    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
#    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
#    worker-threads: 64
#    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
#    # 每块buffer的空间大小,越小的空间被利用越充分
#    buffer-size: 1024
#    # 是否分配的直接内存
#    direct-buffers: true

spring:
  application:
    name: cloud-center-gateway


## 服务注册配置
eureka:
  instance:
    prefer-ip-address: true # 表示：将自己的ip注册到eureka
    host: localhost
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.host}:${eureka.instance.port}/eureka/


# 健康检查基础配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

# 配置日志
logging:
  level:
    cn.com.cloud: DEBUG
  file: ./log/${spring.application.name}/${spring.application.name}.log

